services:
  smart-portal-next-app:
    container_name: smart-portal-next-app
    build:
      context: ./
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
